apiVersion: v1
kind: Service
metadata:
  name: faf-service
  namespace: faf
spec:
  selector:
    app: faf
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000

